### ISSUE TITLE
Adguard DNS name resolution times out with OpenWrt/stubby

### ISSUE THREAD

**Issue by Ryan-Goldstein** [AdguardTeam/AdGuardDNS#150]
I've been using AdGuard DNS for many months by connecting to it via DoT through stubby in my OpenWrt-flashed router, running the latest version of both OpenWrt (19.07.7) and stubby (0.3.0-1).

It had been working well up until about a week ago, when I started seeing resolution timeouts, mostly on Google-related domains, and I understand that that has since been fixed per [this blog post](https://adguard.com/en/blog/dns-google-domains-fixed.html).

In the past few days, possibly corresponding to the changes made to fix the aforementioned timeout issue, I have started experiencing a different issue, where after 5-15 minutes, name resolution stops working on all clients and my router itself. Running nslookup on any domain when my router enters this state results in:

```
;; connection timed out; no servers could be reached
```

There's nothing indicated in the OpenWrt system logs at the debug log level, but name resolution simply stops working, with name resolution attempts timing out. Restarting stubby with `service stubby restart` resolves the issue again for approximately 5-15 minutes longer, at which time the same problem occurs.

Keeping all stubby settings the same, but switching from Adguard DNS to Cloudflare DNS, that issue no longer occurs, so it seems attributable specifically to Adguard DNS.

Here is my stubby configuration with Adguard DNS being used:

```
resolution_type: GETDNS_RESOLUTION_STUB
round_robin_upstreams: 0
appdata_dir: "/var/lib/stubby"
tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
tls_query_padding_blocksize: 128
edns_client_subnet_private: 1
idle_timeout: 10000
listen_addresses:
  - 127.0.0.1@5453
  - 0::1@5453
dns_transport_list:
  - GETDNS_TRANSPORT_TLS
upstream_recursive_servers:
#  - address_data: 1.1.1.1
#    tls_auth_name: "cloudflare-dns.com"
#  - address_data: 1.0.0.1
#    tls_auth_name: "cloudflare-dns.com"
  - address_data: 94.140.14.14
    tls_auth_name: "dns.adguard.com"
  - address_data: 94.140.15.15
    tls_auth_name: "dns.adguard.com"
```

When switching to Cloudflare DNS by removing the commented lines, and commenting out the Adguard DNS lines, then restarting stubby with `service stubby restart`, name resolution works and remains working without having to restart the stubby service.

I'd be happy to provide any other requested information and/or follow any suggested troubleshooting steps. Thanks in advance!
